### ISSUE TITLE
Feature Request: add onAfterContentSave()

### ISSUE THREAD

**Issue by davidpanzarella** [stevewithington/MuraPlugin#2]
I think this can already be done, but wanted a space to confirm that. Am I correct in thinking that I can add this to my extensions/includes/eventHandler.cfc?

```
public any function onAfterContentSave(required struct $) {
    var local = {};
    local.$ = arguments.$;
    set$(arguments.$);

    savecontent variable='local.str' {
        include 'includes/onAfterContentSave.cfm';
    }

    return local.str;
}
```

I can get this to work without a hitch if i do this in my config.xml:

<script runat="onAfterContentSave" scriptfile="scripts/onAfterContentSave.cfm"/>

But it's always good to know best practice!

**Comment by stevewithington** [comment]
@davidpanzarella well, technically it should ... but i'm not sure what you're trying to do. if you're doing something in `onAfterContentSave`, it should probably be something like logging something, or kicking off a service ... not returning something, because the content has already been saved. in short though, yes, it should work.

**Comment by davidpanzarella** [comment]
This actually does work. Thanks Steve!
