### ISSUE TITLE
Display Object config.xml.cfm syntax

### ISSUE THREAD

**Issue by dgibson666** [stevewithington/MuraPlugin#6]
Is there a reason your config.xml.cfm syntax does not match what is on your blog? Are they both valid in Mura 7?  http://www.getmura.com/blog/mura-cms-7-new-display-object-conventions/

**Comment by stevewithington** [comment]
@dgibson666 Are you referring to using `<mura ...>` vs. `<displayobject ...>`? If so, yes, they're both valid, but I'm encouraging people to simply use `<mura ...>`. 

The blog post was written last year, and since then we've made some updates. That said, I could easily update the blog post with the recommended `<mura ...>` tag instead.

**Comment by stevewithington** [comment]
Since this isn't an actual issue, I'm going to close the ticket.

**Comment by dgibson666** [comment]
Yes, that was the difference I meant - thanks!
